# Generated by Django 4.1.7 on 2023-04-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ADAUGDB', '0001_initial'),
        ('BTExamStaffDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTStudentGradePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField()),
                ('sub_id', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('CourseStructure_id', models.IntegerField()),
                ('AYear', models.IntegerField()),
                ('ASem', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('OfferedYear', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('Grade', models.CharField(max_length=2)),
                ('AttGrade', models.CharField(max_length=2)),
                ('Regulation', models.FloatField()),
                ('Creditable', models.IntegerField()),
                ('Credits', models.IntegerField()),
                ('Course_Credits', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=10)),
                ('Points', models.IntegerField()),
                ('GP', models.IntegerField()),
                ('AYASBYBS', models.IntegerField()),
            ],
            options={
                'db_table': 'BTStudentGradePointsMV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BTSubjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AYear', models.IntegerField()),
                ('ASem', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('Regulation', models.FloatField()),
                ('Mode', models.CharField(max_length=1)),
                ('Dept', models.IntegerField()),
                ('SubId', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('Credits', models.IntegerField()),
                ('OfferedBy', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=10)),
                ('DistributionRatio', models.TextField()),
                ('Distribution', models.TextField()),
                ('DistributionNames', models.TextField()),
                ('PromoteThreshold', models.TextField()),
            ],
            options={
                'db_table': 'BTSubjectInfoV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BTRollLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cycle', models.IntegerField(choices=[(10, 'PHYSICS'), (9, 'CHEMISTRY')], default=0)),
                ('Section', models.CharField(default='NA', max_length=2)),
                ('RegEventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADAUGDB.btregistrationstatus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BTExamStaffDB.btstudentinfo')),
            ],
            options={
                'db_table': 'BTRollLists',
                'managed': True,
                'unique_together': {('student', 'RegEventId')},
            },
        ),
        migrations.CreateModel(
            name='BTSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegEventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADAUGDB.btregistrationstatus')),
                ('course', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ADAUGDB.btcourses')),
            ],
            options={
                'db_table': 'BTSubjects',
                'managed': True,
                'unique_together': {('course', 'RegEventId')},
            },
        ),
        migrations.CreateModel(
            name='BTStudentRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mode', models.IntegerField()),
                ('RegEventId', models.ForeignKey(db_column='RegEventId', on_delete=django.db.models.deletion.CASCADE, to='ADAUGDB.btregistrationstatus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BTco_ordinator.btrolllists')),
                ('sub_id', models.ForeignKey(db_column='sub_id', on_delete=django.db.models.deletion.CASCADE, to='BTco_ordinator.btsubjects')),
            ],
            options={
                'db_table': 'BTStudentRegistrations',
                'managed': True,
                'unique_together': {('student', 'RegEventId', 'sub_id')},
            },
        ),
    ]
