# Generated by Django 4.1.7 on 2023-04-29 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BTExamStaffDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=255)),
                ('Credits', models.IntegerField()),
                ('OfferedBy', models.IntegerField()),
                ('lectures', models.IntegerField()),
                ('tutorials', models.IntegerField()),
                ('practicals', models.IntegerField()),
                ('DistributionRatio', models.TextField()),
            ],
            options={
                'db_table': 'BTCourses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BTCourseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('Dept', models.IntegerField()),
                ('Regulation', models.FloatField()),
                ('Category', models.CharField(max_length=10)),
                ('Type', models.CharField(max_length=10)),
                ('Creditable', models.IntegerField()),
                ('Credits', models.IntegerField()),
                ('count', models.IntegerField()),
                ('Rigid', models.BooleanField()),
            ],
            options={
                'db_table': 'BTCourseStructure',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BTHOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.IntegerField()),
                ('AssignedDate', models.DateTimeField(auto_now_add=True)),
                ('RevokeDate', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'BTHOD',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BTMarksDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regulation', models.FloatField()),
                ('Distribution', models.TextField()),
                ('DistributionNames', models.TextField()),
                ('PromoteThreshold', models.TextField()),
            ],
            options={
                'db_table': 'BTMarksDistribution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BTRegistrationstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AYear', models.IntegerField()),
                ('ASem', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('Regulation', models.FloatField()),
                ('Dept', models.IntegerField()),
                ('Mode', models.CharField(max_length=1)),
                ('Status', models.IntegerField()),
                ('RollListstatus', models.IntegerField()),
                ('RollListFeeStatus', models.IntegerField()),
                ('OERollListStatus', models.IntegerField()),
                ('OERegistrationStatus', models.IntegerField()),
                ('RegistrationStatus', models.IntegerField()),
                ('MarksStatus', models.IntegerField()),
                ('Gradestatus', models.IntegerField()),
            ],
            options={
                'db_table': 'BTRegistration_Status',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='btregistrationstatus',
            constraint=models.UniqueConstraint(fields=('AYear', 'ASem', 'BYear', 'BSem', 'Regulation', 'Dept', 'Mode'), name='unique BTRegistrationstatus'),
        ),
        migrations.AlterUniqueTogether(
            name='btmarksdistribution',
            unique_together={('Regulation', 'Distribution', 'DistributionNames', 'PromoteThreshold')},
        ),
        migrations.AddField(
            model_name='bthod',
            name='Faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BTExamStaffDB.btfacultyinfo'),
        ),
        migrations.AddField(
            model_name='bthod',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='btcoursestructure',
            constraint=models.UniqueConstraint(fields=('Category', 'Type', 'Creditable', 'Credits', 'Regulation', 'BYear', 'BSem', 'Dept'), name='Unique BTCourseStructureId'),
        ),
        migrations.AddField(
            model_name='btcourses',
            name='CourseStructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADAUGDB.btcoursestructure'),
        ),
        migrations.AddField(
            model_name='btcourses',
            name='MarkDistribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADAUGDB.btmarksdistribution'),
        ),
        migrations.AlterUniqueTogether(
            name='bthod',
            unique_together={('Faculty', 'Dept', 'AssignedDate')},
        ),
        migrations.AddConstraint(
            model_name='btcourses',
            constraint=models.UniqueConstraint(fields=('SubCode', 'SubName', 'CourseStructure', 'DistributionRatio', 'MarkDistribution'), name='BTCourses_unique_course'),
        ),
    ]
