# Generated by Django 4.1.7 on 2023-04-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTSubjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AYear', models.IntegerField()),
                ('ASem', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('BSem', models.IntegerField()),
                ('Regulation', models.FloatField()),
                ('Mode', models.CharField(max_length=1)),
                ('Dept', models.IntegerField()),
                ('SubId', models.IntegerField()),
                ('SubCode', models.CharField(max_length=10)),
                ('SubName', models.CharField(max_length=100)),
                ('Credits', models.IntegerField()),
                ('OfferedBy', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=10)),
                ('DistributionRatio', models.TextField()),
                ('Distribution', models.TextField()),
                ('DistributionNames', models.TextField()),
                ('PromoteThreshold', models.TextField()),
            ],
            options={
                'db_table': 'BTSubjectInfoV',
                'managed': False,
            },
        ),
    ]
