# Generated by Django 4.1.7 on 2023-04-29 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BTExamStaffDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTFaculty_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignDate', models.DateTimeField(auto_now_add=True)),
                ('RevokeDate', models.DateTimeField(null=True)),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BTExamStaffDB.btfacultyinfo')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BTFaculty_user',
                'managed': True,
                'unique_together': {('User', 'Faculty', 'AssignDate', 'RevokeDate')},
            },
        ),
        migrations.CreateModel(
            name='BTCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.IntegerField()),
                ('BYear', models.IntegerField()),
                ('AssignDate', models.DateTimeField(auto_now_add=True)),
                ('RevokeDate', models.DateTimeField(null=True)),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BTExamStaffDB.btfacultyinfo')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BTFaculty_Coordinator',
                'managed': True,
                'unique_together': {('User', 'Faculty', 'AssignDate', 'RevokeDate')},
            },
        ),
    ]
