# Generated by Django 4.1.7 on 2023-04-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BTco_ordinator', '0001_initial'),
        ('BTfaculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks', models.TextField()),
                ('TotalMarks', models.IntegerField()),
                ('Registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BTco_ordinator.btstudentregistrations')),
            ],
            options={
                'db_table': 'BTMarks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BTStudentGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegEventId', models.IntegerField()),
                ('Regulation', models.FloatField()),
                ('Grade', models.CharField(max_length=2)),
                ('AttGrade', models.CharField(max_length=2)),
                ('RegId', models.ForeignKey(db_column='RegId', on_delete=django.db.models.deletion.CASCADE, to='BTco_ordinator.btstudentregistrations')),
            ],
            options={
                'db_table': 'BTStudentGrades',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='BTStudentInfo',
        ),
        migrations.AddConstraint(
            model_name='btstudentgrades',
            constraint=models.UniqueConstraint(fields=('RegId',), name='unique_BTStudentGrades_registration'),
        ),
        migrations.AddConstraint(
            model_name='btmarks',
            constraint=models.UniqueConstraint(fields=('Registration',), name='unique_BTmarks_registration'),
        ),
    ]
